<?php

namespace DoctrineProxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Party extends \Entities\Party implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Entities\\Party' . "\0" . 'game', 'name', 'user_id', 'userName', 'readyToStart', 'lastUpdate', 'assassinationAttempt', 'assassinationTarget', '' . "\0" . 'Entities\\Party' . "\0" . 'hand', '' . "\0" . 'Entities\\Party' . "\0" . 'senators', 'messages', '' . "\0" . 'Entities\\Party' . "\0" . 'leader', 'treasury');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Entities\\Party' . "\0" . 'game', 'name', 'user_id', 'userName', 'readyToStart', 'lastUpdate', 'assassinationAttempt', 'assassinationTarget', '' . "\0" . 'Entities\\Party' . "\0" . 'hand', '' . "\0" . 'Entities\\Party' . "\0" . 'senators', 'messages', '' . "\0" . 'Entities\\Party' . "\0" . 'leader', 'treasury');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Party $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setGame($game)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGame', array($game));

        return parent::setGame($game);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser_id($user_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser_id', array($user_id));

        return parent::setUser_id($user_id);
    }

    /**
     * {@inheritDoc}
     */
    public function setUserName($userName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserName', array($userName));

        return parent::setUserName($userName);
    }

    /**
     * {@inheritDoc}
     */
    public function setReadyToStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReadyToStart', array());

        return parent::setReadyToStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUpdate($lastUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUpdate', array($lastUpdate));

        return parent::setLastUpdate($lastUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function setAssassinationAttempt($assassinationAttempt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssassinationAttempt', array($assassinationAttempt));

        return parent::setAssassinationAttempt($assassinationAttempt);
    }

    /**
     * {@inheritDoc}
     */
    public function setAssassinationTarget($assassinationTarget)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssassinationTarget', array($assassinationTarget));

        return parent::setAssassinationTarget($assassinationTarget);
    }

    /**
     * {@inheritDoc}
     */
    public function setLeader($leader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeader', array($leader));

        return parent::setLeader($leader);
    }

    /**
     * {@inheritDoc}
     */
    public function setTreasury($treasury)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTreasury', array($treasury));

        return parent::setTreasury($treasury);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getGame()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGame', array());

        return parent::getGame();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser_id()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser_id', array());

        return parent::getUser_id();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserName', array());

        return parent::getUserName();
    }

    /**
     * {@inheritDoc}
     */
    public function getReadyToStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReadyToStart', array());

        return parent::getReadyToStart();
    }

    /**
     * {@inheritDoc}
     */
    public function getHand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHand', array());

        return parent::getHand();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenators()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenators', array());

        return parent::getSenators();
    }

    /**
     * {@inheritDoc}
     */
    public function getMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessages', array());

        return parent::getMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUpdate', array());

        return parent::getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getAssassinationAttempt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssassinationAttempt', array());

        return parent::getAssassinationAttempt();
    }

    /**
     * {@inheritDoc}
     */
    public function getAssassinationTarget()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssassinationTarget', array());

        return parent::getAssassinationTarget();
    }

    /**
     * {@inheritDoc}
     */
    public function getLeader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeader', array());

        return parent::getLeader();
    }

    /**
     * {@inheritDoc}
     */
    public function getTreasury()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTreasury', array());

        return parent::getTreasury();
    }

    /**
     * {@inheritDoc}
     */
    public function saveData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'saveData', array());

        return parent::saveData();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessage', array($message));

        return parent::addMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function joinGame(\Entities\Game $game)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'joinGame', array($game));

        return parent::joinGame($game);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', array());

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalVotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalVotes', array());

        return parent::getTotalVotes();
    }

}
